### ISSUE TITLE
kmodel v4 support?

### ISSUE THREAD

**Issue by kartben** [sipeed/MaixPy-v1#193]
Hi,

Could you please share some pointer w.r.t how I could use a kmodel v4 (converted using nncase 0.2.x)?

Thanks!

**Comment by nnn112358** [comment]
Maixpy ​​only supports up to kmodel v3.
MaixPY's kpu.load function is included in lib_sipeed_kpu.a, but the source has not been released.
I also expect kmodel v4 support.

**Comment by windowsair** [comment]
Hey, here is a preview version:
https://bbs.sipeed.com/t/topic/1790
Unfortunately, it is not included in the latest build.

**Comment by luismeruje** [comment]
Hello, I'm having the same problem. 
I tried compiling from source, since your latest commits talk about having added v4 support.
However, when I try to load my model I get a "core dump: misaligned load  ".
I also tried to compile my model with nncase 0.1.x but it says it does not support Conv2d layers.
Will there be a new release in the near future or is my only alternative to code in C?

**Comment by Neutree** [comment]
try latest firmware, support v4 converted from nncase v2 bata2.0, if some question, open new issue~
