### ISSUE TITLE
Cannot use rshell or ampy

### ISSUE THREAD

**Issue by DurandA** [sipeed/MaixPy-v1#25]
This version of MicroPython is somehow not compatible with *rshell* nor *ampy*. These are tools for interacting with MicroPython's filesystem.

This might be related to non-standard debug output that confuse these tools.

If this issue should not be resolved, what is the most practical way to upload scripts to MaixPy?

**Comment by wipping** [comment]
The current release of MaixPy does not support most of these features, we are developing another version of MaixPy, this version of MaixPy will support the fat file system. In addition, zmodem can be used to transfer small size script files to the development board.

**Comment by DurandA** [comment]
This is awesome!

**Comment by goatchurchprime** [comment]
It worked on my jupyter_micropython_kernel first time!

https://github.com/goatchurchprime/jupyter_micropython_kernel/

The code I tried it out on is here:  https://github.com/goatchurchprime/jupyter_micropython_kernel/blob/master/Maixpy_demo.ipynb

**Comment by robert-hh** [comment]
zmodem file transfer does not work well. The recommended xshell starts, but does not finish. Teraterm works, but is awfully slow (like 50 chars/second).

**Comment by robert-hh** [comment]
I have a patched code (main.c, uart_core.c and mpconfigport.h) here, https://github.com/robert-hh/K210-Stuff, which supports at least some of the ampy commands, like ls and put. ampy get is not supported. It looks as if ampy tries to upload code which fails at MaixPy.

**Comment by robert-hh** [comment]
Ampy get fails, because file read on MaixPy returns '' at the end of the file, and the code ampy uploads expects b'' as the EOF signal. The implementation of file.read() fails here for MaixPy. When opened in mode "rb", like ampy does, file.read() should return a bytes object. Instead that, it returns a string.

**Comment by robert-hh** [comment]
For ampy and rshell I have made a PR that fixes it (https://github.com/sipeed/MaixPy/pull/33). For rshell these changes were required, which are a little bit "hacky": 
- board.name shall return a board name. That can be done by assigning one in boot.py, like 
board.name="maixpy"
- os.stat("/") shall return a tuple with 0x4000 in the first element. Since nitrogen spiffs does not know directories, that would require a special treatment of that name, and I doubt that it is worth the effort.

**Comment by Neutree** [comment]
we support ampy and GUI tool uPyloader now, but not support rshell yet, see [doc](https://maixpy.sipeed.com/en/get_started/upload_script.html)

we will close this issue, and if have question you can reopen or create a new one, thanks
